### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by gdedi001** [Katja-B/prj-rev-bwfs-dasmoto#3]
Dont forget to add the `alt` attribute here
https://github.com/Katja-B/prj-rev-bwfs-dasmoto/blob/master/Dasmotos%20Arts%20and%20Crafts/index.html#L35

**Comment by Katja-B** [comment]
@gdedi001 I'm not sure I understand: do I need to use `alt` attribute for a `span`?

**Comment by gdedi001** [comment]
Sorry I meant to paste your image tag, what you have is correct
